version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQAGitTest2306Project
  gitServerName: SIQA_KVV_IBM
  gitUrl: https://github.com/Karthik-V-IBM-10
  gitUsername: Karthik-V-IBM-10
  gitBranch: main
services:
- serviceName: project.siqagittest2306.integrations:AlertsCRTandERT
  packages:
  - name: SIQAGitTest2306Project
    version: "1.0"
- serviceName: pub.alert:emit
  packages:
  - name: WmPublic
    version: 11.1.0.0.2068
